FROM ubuntu:18.04
RUN apt update \
 && apt install -y \
    curl \
    gnupg \
    gcc \
    g++ \
    make \
 && curl -sL https://deb.nodesource.com/setup_10.16.3 | bash - \
 && apt install -y nodejs \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -p /var/lib/jenkins/workspace/mern_docker/
